
version: '3.8'

volumes:
  shared-file-system:
    driver: local
  vt-src:
    driver: local
  sanitizer-cache:
    driver: local
  vt-cache:
    driver: local

# Define rules for bvh configuration options across various services
x-sanitizeropts: &sanitizeropts
  CMAKE_BUILD_TYPE: ${BUILD_TYPE:-release}
  https_proxy: ${PROXY-}
  http_proxy: ${PROXY-}
  VT_ROOT: ${VT_ROOT:-/vt/install}

services:

  vt-base:
    image: lifflander1/vt:develop
    build:
      context: https://github.com/DARMA-tasking/vt.git#develop
      dockerfile: ci/docker/ubuntu-18.04-clang-cpp.dockerfile
    volumes:
      - shared-file-system:/serialization-sanitizer:delegated
      - vt-src:/vt:delegated
      - vt-cache:/build:delegated

  sanitizer-base:
    image: lifflander1/sanitizer-${COMPILER}-base-image:latest
    build:
      context: .
      target: build
      dockerfile: workflows/ubuntu-18.04-clang-cpp.dockerfile
      args: &default-args
        arch: ${ARCH}
        proxy: ${PROXY}
        compiler: ${COMPILER}
    environment:
      <<: *sanitizeropts
    volumes:
      - shared-file-system:/build/serialization-sanitizer:delegated
      - .:/serialization-sanitizer:delegated
      - sanitizer-cache:/build:delegated
      - vt-src:/vt:delegated
