
version: '3.8'

volumes:
  shared-file-system:
    driver: local
  vt-src:
    driver: local
  vt-cache:
    driver: local
  vt-build:
    driver: local

# Define rules for sanitizer configuration options across various services
x-sanitizeropts: &sanitizeropts
  CMAKE_BUILD_TYPE: ${BUILD_TYPE:-release}
  https_proxy: ${PROXY-}
  http_proxy: ${PROXY-}

services:

  vt-base:
    image: lifflander1/vt:develop
    build:
      context: https://github.com/DARMA-tasking/vt.git#develop
      dockerfile: ci/docker/ubuntu-18.04-clang-cpp.dockerfile
      args: &default-args
        arch: ${ARCH}
        proxy: ${PROXY}
        compiler: ${COMPILER}
    volumes:
      - shared-file-system:/serialization-sanitizer:delegated
      - vt-cache:/build:delegated
      - vt-build:/build/vt:delegated

  sanitizer-base:
    image: lifflander1/sanitizer-${COMPILER}-base-image:latest
    build:
      context: .
      target: build
      dockerfile: workflows/ubuntu-18.04-clang-cpp.dockerfile
      args: *default-args
    environment:
      <<: *sanitizeropts
    volumes:
      - shared-file-system:/build/serialization-sanitizer:delegated
      - .:/serialization-sanitizer:delegated
      - vt-build:/vt:delegated
    command:
      /bin/bash -c "
        /serialization-sanitizer/workflows/build_cpp.sh /serialization-sanitizer /build &&
        /serialization-sanitizer/workflows/test_cpp.sh /serialization-sanitizer /build"
